### PR TITLE
Org Updates, prior PRs

### PR DESCRIPTION
**Pull request by SteveLLamb**
Incorporate changes from prior PRs not merged, into new HTML format:
- https://github.com/SMPTE/ag-10/pull/22/files
- https://github.com/SMPTE/ag-10/pull/3/files
- https://github.com/SMPTE/ag-10/pull/18/files
- https://github.com/SMPTE/ag-10/pull/17/files
- https://github.com/SMPTE/ag-10/pull/16/files
- https://github.com/SMPTE/ag-10/pull/13/files

@SMPTE/svp - Will close out old PRs when this is approved.

### CODE REVIEW

**Review by palemieux — APPROVED** [review]

**Comment by SteveLLamb** [comment]
Notice to be sent to ST - this PR is under 2-week review, and will be merged on 2023-04-10 if no objections.

**Comment by SteveLLamb** [comment]
Update to remove ATSC contact as per ST meeting 2023-03-28 https://github.com/SMPTE/ag-10/pull/24/commits/009c5ede796de10d8ec1203b2ff9eaf20c1b1798

**Review by tbause — APPROVED** [review]
Looks good

**Comment by SteveLLamb** [comment]
Merging as per above, no objections from ST.

**Pull request merged**
