### PR TITLE
conform to html-pub-template

### PR DESCRIPTION
**Pull request by SteveLLamb**
- added tooling submodule from https://github.com/SMPTE/html-pub

General updates from template on `index.html`
- update head and default sections as per above
- changed styling for section names as per above
- added table caption and id as per above

### CODE REVIEW

**Comment by palemieux** [comment]
@SteveLLamb Is this still up-to-date?

**Review by palemieux — APPROVED** [review]

**Comment by SteveLLamb** [comment]
> @SteveLLamb Is this still up-to-date?

@palemieux Yes, minus the updates provided by the PR done by user https://github.com/sh-smpte - not sure who it is, as they are not in the ST team, nor the SMPTE org in Github in general.

**Comment by SteveLLamb** [comment]
@palemieux BTW, for this all other PRs - I'll wait to merge this PR until we review in ST, as from the AG itself - `AG-10 is a public AG and revision requires Standards Committee (ST)  approval`.

**Comment by SteveLLamb** [comment]
@palemieux We'll have to update this one with the new tooling. I'll mark this as draft for now for breadcrumb.

**Comment by palemieux** [comment]
Ok. You can update to the new tooling today.

**Comment by SteveLLamb** [comment]
Closing this PR to grab newest updates, too many conflict to resolve.

**Pull request closed without merging**
