### PR TITLE
Org Updates

### PR DESCRIPTION
**Pull request by sh-smpte**
Deleted DECE from Org list

### CODE REVIEW

**Comment by palemieux** [comment]
In the future, it would be ideal to create one pull request per org... but I guess we are doing a batch update.

I would not write _TBD_, but instead leave the box empty or use _N/A_.

Have we made a call for volunteers for the N/A liaisons?

At what point do we remove the liaison if there is no individual?

**Comment by sh-smpte** [comment]
> In the future, it would be ideal to create one pull request per org... but I guess we are doing a batch update.

Understood - will do going forward!

> I would not write _TBD_, but instead leave the box empty or use _N/A_.
> Have we made a call for volunteers for the N/A liaisons?
> At what point do we remove the liaison if there is no individual?

I was thinking of simply deleting all org that doesn't have 1. both rep on Org and SMPTE side, 2. Ask at ST if anyone wants to volunteer as liaison for org that's missing SMPTE rep - and if not, delete that as well... what do you think?

**Comment by fschleich** [comment]
@sh-smpte - can you split this up into separate PRs (with brief description of the change) for each org update? I believe some of the updates are straight forward and could be approved by ST (e.g. IEEE P1588 updates), while others may need more work/discussion (e.g. what to do with ARIB; who is the org contact for ISO TC 42).

**Comment by SteveLLamb** [comment]
Not sure if this was merged, but The PR will need to be redone to conform with new tooling in implemented in https://github.com/SMPTE/ag-10/pull/23

**Comment by SteveLLamb** [comment]
resolved in https://github.com/SMPTE/ag-10/pull/24

**Pull request closed without merging**
